name: influxdb_client
version: 2.0.0
description: A client library for quering, writing and managing InfluxDB 2.0
homepage: https://github.com/influxdata/influxdb-client-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: '>=2.0.13 <=3.1.2'
  http: '>=0.13.0 <0.14.0'
  csv: '>=4.1.0 <6.0.0'
  universal_io: ^2.0.4
  intl: ^0.17.0
  meta: ^1.1.8

dev_dependencies:
  build_runner: any
  build_test: any
  json_serializable: any
  mockito: any
  collection: any
  test: any
